import type { CinemaFilm } from './cinema-data';
import type { SuperHoverListItem } from '@/registry/crafterui/ui/super-hover-list';

export interface ArchiveFilmItem extends SuperHoverListItem {
  id: number;
  title: string;
  subtitle: string; // Director · Genre
  meta: string; // Year
  image: string; // Cover art
  category: string;
  imdbRating: string;
  duration: string;
  tagline: string;
  synopsis: string;
}

export const ARCHIVE_FILMS: ArchiveFilmItem[] = [
  {
    id: 1,
    title: "The Godfather",
    subtitle: "Francis Ford Coppola · Crime / Drama",
    meta: "1972",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1200&q=80",
    category: "Crime · Drama · Classic",
    imdbRating: "9.2",
    duration: "2h 55m",
    tagline: "An offer you can't refuse.",
    synopsis: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.",
  },
  {
    id: 2,
    title: "2001: A Space Odyssey",
    subtitle: "Stanley Kubrick · Sci-Fi / Epic",
    meta: "1968",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    category: "Sci-Fi · Mystery · Masterpiece",
    imdbRating: "8.3",
    duration: "2h 29m",
    tagline: "The ultimate trip.",
    synopsis: "After uncovering a mysterious artifact buried beneath the lunar surface, a spacecraft manned by two astronauts and a supercomputer is sent to Jupiter to investigate its origins.",
  },
  {
    id: 3,
    title: "Blade Runner 2049",
    subtitle: "Denis Villeneuve · Cyberpunk / Noir",
    meta: "2017",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    category: "Sci-Fi · Thriller · Cyberpunk",
    imdbRating: "8.0",
    duration: "2h 44m",
    tagline: "The key to the future is finally unearthed.",
    synopsis: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
  },
  {
    id: 4,
    title: "Spider-Man: Brand New Day",
    subtitle: "Destin Daniel Cretton · Action / Sci-Fi",
    meta: "2026",
    image: "https://images.unsplash.com/photo-1604200213928-ba3cf4fc8436?auto=format&fit=crop&w=1200&q=80",
    category: "Action · Adventure · Sci-Fi",
    imdbRating: "8.4",
    duration: "2h 22m",
    tagline: "With great responsibility comes a brand new dawn.",
    synopsis: "Peter Parker navigates life completely stripped of his past identity, forging a raw, grounded vigilante presence through the rain-soaked winter rooftops of New York City.",
  },
  {
    id: 5,
    title: "Apocalypse Now: Final Cut",
    subtitle: "Francis Ford Coppola · War / Drama",
    meta: "1979",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    category: "War · Drama · Hallucinatory",
    imdbRating: "8.4",
    duration: "3h 02m",
    tagline: "The horror... the horror.",
    synopsis: "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.",
  },
  {
    id: 6,
    title: "Weapons",
    subtitle: "Zach Cregger · Mystery / Horror",
    meta: "2026",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    category: "Horror · Mystery · Thriller",
    imdbRating: "7.8",
    duration: "1h 58m",
    tagline: "Every truth is armed.",
    synopsis: "An interrelated, multi-story horror epic tracking the midnight disappearance of high school seniors in a small Florida town.",
  },
  {
    id: 7,
    title: "In the Mood for Love",
    subtitle: "Wong Kar-wai · Romance / Art House",
    meta: "2000",
    image: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?auto=format&fit=crop&w=1200&q=80",
    category: "Romance · Drama · Criterion",
    imdbRating: "8.1",
    duration: "1h 38m",
    tagline: "He remembers those vanished years.",
    synopsis: "Two neighbors form a bond after both suspect extramarital activities of their spouses. However, they agree to keep their bond platonic so as not to commit the same wrongs.",
  },
  {
    id: 8,
    title: "Stalker",
    subtitle: "Andrei Tarkovsky · Sci-Fi / Philosophical",
    meta: "1979",
    image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1200&q=80",
    category: "Sci-Fi · Drama · Soviet Cinema",
    imdbRating: "8.1",
    duration: "2h 42m",
    tagline: "Enter the Zone.",
    synopsis: "A guide leads two men through an area known as the Zone to find a room that grants a person's innermost desires.",
  },
  {
    id: 9,
    title: "Barbarian",
    subtitle: "Zach Cregger · Thriller / Horror",
    meta: "2022",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80",
    category: "Horror · Thriller · Cult",
    imdbRating: "7.0",
    duration: "1h 42m",
    tagline: "Some stay here. Some leave here. Some never get out.",
    synopsis: "A woman staying at an Airbnb discovers that the house she booked is not what it seems.",
  },
  {
    id: 10,
    title: "Mulholland Drive",
    subtitle: "David Lynch · Mystery / Surreal",
    meta: "2001",
    image: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1200&q=80",
    category: "Mystery · Drama · Neo-Noir",
    imdbRating: "7.9",
    duration: "2h 27m",
    tagline: "A love story in the city of dreams.",
    synopsis: "After a car wreck on the winding Mulholland Drive renders a woman amnesiac, she and a perky Hollywood-hopeful search for clues and answers across Los Angeles in a twisting venture beyond dreams and reality.",
  },
  {
    id: 11,
    title: "The Drama",
    subtitle: "Kristoffer Borgli · Romance / Comedy",
    meta: "2026",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&q=80",
    category: "Romance · Drama · Comedy",
    imdbRating: "7.5",
    duration: "1h 52m",
    tagline: "Love is a rehearsal.",
    synopsis: "In the days leading up to what should be their picture-perfect wedding day, unexpected revelations derail what was supposed to be a simple celebration.",
  },
  {
    id: 12,
    title: "Dune: Part Two",
    subtitle: "Denis Villeneuve · Sci-Fi / Adventure",
    meta: "2024",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    category: "Sci-Fi · Adventure",
    imdbRating: "8.5",
    duration: "2h 46m",
    tagline: "Long live the fighters.",
    synopsis: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
  },
  {
    id: 13,
    title: "Resident Evil",
    subtitle: "Paul W.S. Anderson · Action / Horror",
    meta: "2002",
    image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80",
    category: "Sci-Fi · Action · Horror",
    imdbRating: "6.7",
    duration: "1h 40m",
    tagline: "Survive the Hive.",
    synopsis: "A special military unit fights a powerful, out-of-control supercomputer and hundreds of scientists who have mutated into flesh-eating creatures.",
  },
  {
    id: 14,
    title: "Chungking Express",
    subtitle: "Wong Kar-wai · Romance / Comedy",
    meta: "1994",
    image: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1200&q=80",
    category: "Romance · Drama · Hong Kong Wave",
    imdbRating: "8.0",
    duration: "1h 42m",
    tagline: "If my memory of her has an expiration date, let it be 10,000 years.",
    synopsis: "Two melancholic Hong Kong policemen fall in love: one with a mysterious female underworld figure, and the other with a quirky waitress at a late-night restaurant.",
  },
  {
    id: 15,
    title: "Sacrifice",
    subtitle: "Romain Gavras · Art House / Mystery",
    meta: "2025",
    image: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?auto=format&fit=crop&w=1200&q=80",
    category: "Art House · Drama · Mystery",
    imdbRating: "8.1",
    duration: "2h 10m",
    tagline: "Faith is the ultimate fire.",
    synopsis: "A high-society charity gala held on a secluded volcanic island is violently hijacked by a passionate neo-spiritual militia demanding reparations for the Earth.",
  },
  {
    id: 16,
    title: "Taxi Driver",
    subtitle: "Martin Scorsese · Neo-Noir / Crime",
    meta: "1976",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    category: "Crime · Drama · Neo-Noir",
    imdbRating: "8.2",
    duration: "1h 54m",
    tagline: "On every street in every city, there's a nobody who dreams of being a somebody.",
    synopsis: "A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.",
  },
  {
    id: 17,
    title: "Seven Samurai",
    subtitle: "Akira Kurosawa · Action / Drama",
    meta: "1954",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1200&q=80",
    category: "Action · Drama · Masterpiece",
    imdbRating: "8.6",
    duration: "3h 27m",
    tagline: "The magnificent seven samurai who defended a helpless village.",
    synopsis: "Farmers from a village exploited by bandits hire a veteran samurai for protection, who gathers six other samurai to join him.",
  },
  {
    id: 18,
    title: "Alien: Director's Cut",
    subtitle: "Ridley Scott · Sci-Fi / Horror",
    meta: "1979",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    category: "Sci-Fi · Horror · Archival",
    imdbRating: "8.5",
    duration: "1h 57m",
    tagline: "In space no one can hear you scream.",
    synopsis: "The crew of a commercial spacecraft encounters a deadly lifeform after investigating a mysterious transmission of unknown origin on an uncharted planetoid.",
  },
  {
    id: 19,
    title: "Parasite",
    subtitle: "Bong Joon-ho · Thriller / Drama",
    meta: "2019",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80",
    category: "Drama · Thriller · Palme d'Or",
    imdbRating: "8.5",
    duration: "2h 12m",
    tagline: "Act like you own the place.",
    synopsis: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
  },
  {
    id: 20,
    title: "There Will Be Blood",
    subtitle: "Paul Thomas Anderson · Drama / Historical",
    meta: "2007",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    category: "Drama · Masterpiece · Epic",
    imdbRating: "8.2",
    duration: "2h 38m",
    tagline: "There will be a reckoning.",
    synopsis: "A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.",
  },
  {
    id: 21,
    title: "La Haine",
    subtitle: "Mathieu Kassovitz · Drama / Crime",
    meta: "1995",
    image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1200&q=80",
    category: "Drama · Crime · B&W Masterpiece",
    imdbRating: "8.1",
    duration: "1h 38m",
    tagline: "How you fall doesn't matter. It's how you land.",
    synopsis: "Three young friends from a diverse immigrant suburb of Paris spend 24 hours following the aftermath of a violent riot.",
  },
  {
    id: 22,
    title: "Interstellar",
    subtitle: "Christopher Nolan · Sci-Fi / Adventure",
    meta: "2014",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    category: "Sci-Fi · Adventure · Drama",
    imdbRating: "8.7",
    duration: "2h 49m",
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    synopsis: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
  },
  {
    id: 23,
    title: "Solaris",
    subtitle: "Andrei Tarkovsky · Sci-Fi / Psychological",
    meta: "1972",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    category: "Sci-Fi · Mystery · Soviet Cinema",
    imdbRating: "8.0",
    duration: "2h 47m",
    tagline: "The ocean remembers.",
    synopsis: "A psychologist is sent to a space station orbiting a mysterious planet in order to investigate the psychological crisis of the crew.",
  },
  {
    id: 24,
    title: "Drive",
    subtitle: "Nicolas Winding Refn · Action / Neo-Noir",
    meta: "2011",
    image: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1200&q=80",
    category: "Action · Drama · Neo-Noir",
    imdbRating: "7.8",
    duration: "1h 40m",
    tagline: "There are no clean getaways.",
    synopsis: "A mysterious Hollywood action film stuntman gets in trouble with gangsters when he tries to help his neighbor's husband rob a pawn shop while serving as his getaway driver.",
  },
  {
    id: 25,
    title: "Pulp Fiction",
    subtitle: "Quentin Tarantino · Crime / Drama",
    meta: "1994",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1200&q=80",
    category: "Crime · Drama · Palme d'Or",
    imdbRating: "8.9",
    duration: "2h 34m",
    tagline: "You won't know the facts until you've seen the fiction.",
    synopsis: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
  },
  {
    id: 26,
    title: "The Shining",
    subtitle: "Stanley Kubrick · Psychological Horror",
    meta: "1980",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80",
    category: "Horror · Mystery · Cult Classic",
    imdbRating: "8.4",
    duration: "2h 26m",
    tagline: "All work and no play makes Jack a dull boy.",
    synopsis: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
  },
  {
    id: 27,
    title: "Portrait of a Lady on Fire",
    subtitle: "Céline Sciamma · Romance / Drama",
    meta: "2019",
    image: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?auto=format&fit=crop&w=1200&q=80",
    category: "Romance · Drama · French Cinema",
    imdbRating: "8.1",
    duration: "2h 02m",
    tagline: "Do not regret. Remember.",
    synopsis: "On an isolated island in Brittany at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman in secret.",
  },
  {
    id: 28,
    title: "Heat",
    subtitle: "Michael Mann · Crime / Thriller",
    meta: "1995",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    category: "Crime · Drama · Thriller",
    imdbRating: "8.3",
    duration: "2h 50m",
    tagline: "A Los Angeles crime saga.",
    synopsis: "A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.",
  },
  {
    id: 29,
    title: "The Lighthouse",
    subtitle: "Robert Eggers · Psychological Drama",
    meta: "2019",
    image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1200&q=80",
    category: "Horror · Mystery · A24",
    imdbRating: "7.4",
    duration: "1h 49m",
    tagline: "There is enchantment in the light.",
    synopsis: "Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s.",
  },
  {
    id: 30,
    title: "City of God",
    subtitle: "Fernando Meirelles · Crime / Drama",
    meta: "2002",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&q=80",
    category: "Crime · Drama · Brazilian Masterwork",
    imdbRating: "8.6",
    duration: "2h 10m",
    tagline: "Fight and you'll never survive. Run and you'll never escape.",
    synopsis: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
  },
  {
    id: 31,
    title: "No Country for Old Men",
    subtitle: "Joel & Ethan Coen · Crime / Thriller",
    meta: "2007",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    category: "Crime · Drama · Neo-Western",
    imdbRating: "8.2",
    duration: "2h 02m",
    tagline: "There are no clean getaways.",
    synopsis: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
  },
  {
    id: 32,
    title: "Ran",
    subtitle: "Akira Kurosawa · Action / Historical Drama",
    meta: "1985",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1200&q=80",
    category: "Action · Drama · Epic",
    imdbRating: "8.2",
    duration: "2h 40m",
    tagline: "In a world of betrayal, honor was the first casualty.",
    synopsis: "In Medieval Japan, an elderly warlord retires, handing over power to his three sons. However, he grossly underestimates how the new-found power will corrupt them.",
  },
];
