import type { CinemaFilm } from './cinema-data';
import type { SuperHoverListItem } from '@/registry/crafterui/ui/super-hover-list';

export interface ArchiveFilmItem extends SuperHoverListItem {
  id: number;
  title: string;
  subtitle: string; // Director · Genre
  meta: string; // Year
  image: string; // Cover art
  category: string;
  imdbRating: string;
  duration: string;
  tagline: string;
  synopsis: string;
}

export const ARCHIVE_FILMS: ArchiveFilmItem[] = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    subtitle: "Frank Darabont · Drama",
    meta: "1994",
    image: "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Drama · Crime · Masterpiece",
    imdbRating: "9.3",
    duration: "2h 22m",
    tagline: "Fear can hold you prisoner. Hope can set you free.",
    synopsis: "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. Over decades, he befriends fellow inmate Red and discovers solace and redemption through acts of common decency.",
  },
  {
    id: 2,
    title: "The Godfather",
    subtitle: "Francis Ford Coppola · Crime / Drama",
    meta: "1972",
    image: "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Crime · Drama · Classic",
    imdbRating: "9.2",
    duration: "2h 55m",
    tagline: "An offer you can't refuse.",
    synopsis: "The aging patriarch of an organized crime dynasty in postwar New York transfers control of his clandestine empire to his reluctant youngest son, Michael, plunging the family into a ruthless mafia conflict.",
  },
  {
    id: 3,
    title: "The Dark Knight",
    subtitle: "Christopher Nolan · Action / Crime",
    meta: "2008",
    image: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
    category: "Action · Crime · Drama",
    imdbRating: "9.1",
    duration: "2h 32m",
    tagline: "Why so serious?",
    synopsis: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
  },
  {
    id: 4,
    title: "The Godfather Part II",
    subtitle: "Francis Ford Coppola · Crime / Drama",
    meta: "1974",
    image: "https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Crime · Drama · Classic",
    imdbRating: "9.0",
    duration: "3h 22m",
    tagline: "All the power on earth can't change destiny.",
    synopsis: "The continuing saga of the Corleone crime family contrasts the rise of a young Vito Corleone in 1910s New York with the moral descent of his son Michael in the 1950s as he expands into Las Vegas and Cuba.",
  },
  {
    id: 5,
    title: "The Lord of the Rings: The Return of the King",
    subtitle: "Peter Jackson · Fantasy / Adventure",
    meta: "2003",
    image: "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Adventure · Drama · Fantasy",
    imdbRating: "9.0",
    duration: "3h 21m",
    tagline: "The eye of the enemy is moving.",
    synopsis: "The final confrontation between the forces of good and evil for the future of Middle-earth. Frodo and Sam reach Mordor to destroy the One Ring, while Aragorn leads the World of Men against Sauron's army at Minas Tirith.",
  },
  {
    id: 6,
    title: "12 Angry Men",
    subtitle: "Sidney Lumet · Crime / Drama",
    meta: "1957",
    image: "https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Crime · Drama · Classic",
    imdbRating: "9.0",
    duration: "1h 36m",
    tagline: "Life is in their hands. Death is on their minds.",
    synopsis: "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to carefully reconsider the evidence before condemning a young man to the electric chair.",
  },
  {
    id: 7,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    subtitle: "Peter Jackson · Fantasy / Adventure",
    meta: "2001",
    image: "https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Adventure · Drama · Fantasy",
    imdbRating: "8.9",
    duration: "2h 58m",
    tagline: "One ring to rule them all.",
    synopsis: "A meek Hobbit from the Shire and eight companions set out on an epic quest across Middle-earth to destroy the One Ring in the fires of Mount Doom and end the dark dominion of Sauron.",
  },
  {
    id: 8,
    title: "Pulp Fiction",
    subtitle: "Quentin Tarantino · Crime / Noir",
    meta: "1994",
    image: "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Crime · Drama · Cult",
    imdbRating: "8.8",
    duration: "2h 34m",
    tagline: "You won't know the facts until you've seen the fiction.",
    synopsis: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four non-linear tales of violence, dark humor, and unexpected redemption in Los Angeles.",
  },
  {
    id: 9,
    title: "Fight Club",
    subtitle: "David Fincher · Drama / Thriller",
    meta: "1999",
    image: "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Crime · Drama · Thriller",
    imdbRating: "8.8",
    duration: "2h 19m",
    tagline: "Mischief. Mayhem. Soap.",
    synopsis: "An insomniac office worker looking for a way to break free from consumerist numbness meets charismatic soap maker Tyler Durden, co-founding an underground fight club that escalates into an anarchic revolution.",
  },
  {
    id: 10,
    title: "Gladiator",
    subtitle: "Ridley Scott · Action / Historical",
    meta: "2000",
    image: "https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Action · Adventure · Drama",
    imdbRating: "8.5",
    duration: "2h 35m",
    tagline: "What we do in life echoes in eternity.",
    synopsis: "Betrayed and enslaved after the death of Emperor Marcus Aurelius, former Roman general Maximus Decimus Meridius rises through the gladiatorial ranks of the Colosseum to avenge the murder of his family.",
  },
  {
    id: 11,
    title: "Spider-Man: Across the Spider-Verse",
    subtitle: "Joaquim Dos Santos · Animation / Action",
    meta: "2023",
    image: "https://m.media-amazon.com/images/M/MV5BNThiZjA3MjItZGY5Ni00ZmJhLWEwN2EtOTBlYTA4Y2E0M2ZmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Animation · Action · Adventure",
    imdbRating: "8.5",
    duration: "2h 20m",
    tagline: "It's how you wear the mask that matters.",
    synopsis: "Miles Morales catapults across the Multiverse to encounter the Spider Society, charged with protecting reality's fabric. Clashing over how to stop a catastrophic anomaly, Miles must redefine heroism on his own terms.",
  },
  {
    id: 12,
    title: "Whiplash",
    subtitle: "Damien Chazelle · Drama / Music",
    meta: "2014",
    image: "https://m.media-amazon.com/images/M/MV5BMDFjOWFkYzktYzhhMC00NmYyLTkwY2EtYjViMDhmNzg0OGFkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    category: "Drama · Music · Masterpiece",
    imdbRating: "8.5",
    duration: "1h 46m",
    tagline: "The road to greatness can take you to the edge.",
    synopsis: "A fiercely ambitious 19-year-old jazz drummer is pushed past his mental and physical limits by Terence Fletcher, a ruthlessly perfectionist instructor at America's top music conservatory.",
  },
];
